### ISSUE TITLE
Add a "delete" endpoint for jobs and events

### ISSUE THREAD

**Issue by llunaplanet** [VLCTechHub/VLCTechHub-api#34]
When a job / event is published, generate an email for the creator including a link that allows him/her to delete the job / event. The link should be secure including some kind of unique / random token.

**Comment by hell03610** [comment]
I think event management is secondary, as event registration is done more anonymously at the moment.  Also, many of the events published in the website were not posted by the real organizers. We are not asking for any personal information to get back to the publisher or organizer. So maybe another approach would be needed in this case, if needed.

But for jobs it is a great feature. Job offers are entered 99% of the case by the responsible company of the offer and we are already asking for an email contact in the job form (email is not published, it is used in case there is any question with the job offer). This email  address could be use to send an automatic mail with a management link to unpublish the job offer once the job offer gets published.

I would unpublish a job offer, but never delete it. 
Question would be if publish token would be still "active"/working for an unpublished job offer, or a new publish token should be generated.

It would be a great feature ^_^
